### ISSUE TITLE
クチコミを本人許可取ってから公開にする

### ISSUE THREAD

**Issue by Kouch-Sato** [Kouch-Sato/Voil#149]
- reviewsにカラムを追加
- 管理画面で「公開ボタン」を押せるようにする
- 非公開のものは、userの画面から見えないようにする

**Comment by Kouch-Sato** [comment]
adminからのリンクを、adminのpreviewのリンクにする

**Comment by Kouch-Sato** [comment]
status、ってカラムを追加して、enumとかにしたらよろし！
この時、true, falseにしない方がいい
未公開10, 公開20, 削除30とかにできる

**Comment by Kouch-Sato** [comment]
今の非公開reviewをユーザーから隠す。
showも含めて！

**Comment by kota-shidara** [comment]
- previewはつくらない
- review_idをハッシュ化する
=> userは直打ちできない、adminからはアクセスできる！
